"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['uncolorblind.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'aux/apple_rainbow.png'
}

setup(
    app=APP,
    name='uncolorblind',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
